### ISSUE TITLE
Can money-rails work with a decimal column?

### ISSUE THREAD

**Issue by Peeja** [RubyMoney/money-rails#106]
I have a column which stores money amounts in dollars, as a decimal with two decimal places. Can I now monetize that column in my model and start working with Money objects, or do I need to convert the column to an integer column multiply the values by 100 first?

I searched, but I was surprised not to find any information on how to use decimals and money-rails together, since they're the two most suggested solutions to storing monetary amounts in Rails.

**Comment by garrettlancaster** [comment]
Our application has a pricing catalog where our customers price materials by fractional cents.  Is there no way to allow all of my currencies to do this without creating a duplicate currency for each one?

**Comment by georgemillo** [comment]
@garrettlancaster, here's something I've used in one of my projects, you could try using something similar?

    MoneyRails.configure do |config|
      config.register_currency = {
        :priority            => 1,
        :iso_code            => "US8",
        :name                => "US$ with subunit of 8 digits",
        :symbol              => "$",
        :symbol_first        => true,
        :subunit             => "microcent",
        :subunit_to_unit     => 100_000_000,
        :thousands_separator => ",",
        :decimal_mark        => "."
      }

      config.add_rate "US8", "USD", 1
      config.add_rate "USD", "US8", 1

**Comment by tommyalvarez** [comment]
Instead of duplicating exiting currencies and customizing them, you can deregister and re-register them. I found this solution to be quite good from the following stackoverflow post: https://stackoverflow.com/questions/16130225/rails-money-gem-money-formatting-with-2-cent-digits-but-storing-4-cent-digits.

In short, in an initializer do this:

```
currencies = Money::Currency.table.dup

currencies.each do |code, currency|
  Money::Currency.unregister(currency)
end

currencies.each do |code, currency|
  Money::Currency.register(currency.merge({subunit_to_unit: 1000}))
end
```
Had to google a lot to find this.

**Comment by nerburish** [comment]
Hi all, 
There has been any change on this issue?
I have a mysql db with prices stored as decimal (8 precision with 2 decimals) and that cannot be changed easily.
However, I want to use the Money logic (convert to cents, exchanges, etc).

Its possible to use money-rails with this column type or is mandatory use integer or decimal without comma digits?

If it is not possible, I think that would be a nice improvement because decimal column is also widely used to store currency amounts.

Greetings

**Comment by antstorm** [comment]
@nerburish agree, this does sound like a good improvement. I think this can be achieved via adding a new option to the backend. Would you be up for submitting a PR? Happy to help you with getting it merged

**Comment by nerburish** [comment]
Hi @antstorm, 
I could give it a try. However, I never used money-rails before and then don't know how it works in detail. 
I was thinking to use it in my app until I saw that limitation.

**Comment by nerburish** [comment]
Hi again, @antstorm 
I was looking inside the code and trying some "hacks" and could get an idea that could work.
However, I'm not sure if this could have futher implications as I saw that the code have many cases depending the Dbs, config, etc...

At first, I tried to set the config as decimal with options that we need (precision and scale). 
Since the gem delegates in migration column options it creates the columns correctly (tested with mysql)

  config.amount_column = { prefix: '',           # column name prefix
                           postfix: '_amount',    # column name  postfix
                           column_name: nil,     # full column name (overrides prefix, postfix and accessor name)
                           type: :decimal,       # column type
                           present: true,        # column will be created
                           null: false,          # other options will be treated as column options
                           default: 0,
                           **precision: 8,**
                           **scale: 2**
                         }

Then, I saw that there are two main methods: **read_monetized** and **write_monetized**

The "philosophy" of the gem is manage the money as integer.
To accomplish this, the gem does some processes but at the end of the path we always have an integer that would be written into the DB, and a getter that will read that integer.

Before save the integer, we could check if the column configurated as decimal. If its the case we can check the scalar option (for exemple 2)
Then we know already that the integer expected to divide that amount to get the real decimal that must to be stored:

For exemple, for price 50.22$
The subunit integer stored by money-rails would be 5022.
Then, as we have an scalar 2: 5022 / 10 ^ 2 = 50.22

Finally, for the reader, we need to do the same multiplying that decimal to get again the integer expected by the gem.

Greetings

**Comment by antstorm** [comment]
@nerburish glad you're looking into this. So to make matters easier — the conversion between int and decimal can be performed the core `money` gem. You should be able to do something like `Money.new(int_amount).to_f` and then `Money.from_amount(decimal_amount)`

**Comment by mtomov** [comment]
Hey, I also think that official support for decimal storage would be nice as oftentimes we work with the data via direct sql, and it's a bit annoying to always divide by 100.

Thank you!
