### ISSUE TITLE
validates :numericality with allow_nil: true does not work

### ISSUE THREAD

**Issue by Goltergaul** [RubyMoney/money-rails#180]
I have the following mongoid document

```
class Movie
  include Mongoid::Document
  field :fee,    type: Money
  validates :fee,  numericality: { greater_than_or_equal_to: 0.0 }, allow_nil: true
end
```

I also have a standard form to create that movie. But if i enter nothing in the fee formfield, my movie looks like this: `@movie.fee => #<Money fractional:0 currency:EUR>` which is not nil. Shouldn't it be nil?

In addition the field is not valid. (which makes no sense since the value is 0 cents which is greater than 0.0) But if i enter 21 in my field, then it is suddenly valid.

I saw that in activerecord i can do something like
    monetize :fee, :allow_nil => true,
      :numericality => {
        :greater_than_or_equal_to => 0
      }

Can I use that with mongodb?

**Comment by alexadept** [comment]
it apears due to

`gems/activemodel-5.0.6/lib/active_model/validations/numericality.rb:23`

`
   20:       def validate_each(record, attr_name, value)
   21:         before_type_cast = :"#{attr_name}_before_type_cast"
   22:
=> 23:         raw_value = record.send(before_type_cast) if record.respond_to?(before_type_cast) && record.send(before_type_cast) != value
   24:         raw_value ||= value
`

where `value` - is our Money attribute
eg. in my case i have a 
`(byebug) value
#<Money fractional:200000 currency:RUB>
(byebug) record.send(before_type_cast)
2000`

when `2000 != Money.from_amount(200000)` will raise exception
I wrote my custom validation method. It is quite easy, but this mistake waste time

**Comment by antstorm** [comment]
@alexadept can you share how your validations is defined? Thank you!
