### ISSUE TITLE
Sum money-rails using Mongoid?

### ISSUE THREAD

**Issue by netwire88** [RubyMoney/money-rails#283]
Hi,
I'm using RubyMoney (money-rails) with Mongoid v3. Something like this:

    class Order
      include Mongoid::Document
    	field :order_amount, :type => Money, :default => Money.new(0)
    	...
    end

How can I aggregate on a `Money` field? For example, when I run `Order.sum(:order_amount)`, I get `0` even if the field has a value like `#<Money fractional:5500 currency:USD>`. I've also tried `Order.sum(:order_amount_cents)` and that also returns `0`.

This is the generated Ruby MongoDB command:

    command={:aggregate=>"orders", :pipeline=>[{"$match"=>{"order_amount"=>{"$nin"=>[nil]}}}, {"$group"=>{"_id"=>"order_amount", "count"=>{"$sum"=>1}, "max"=>{"$max"=>"$order_amount"}, "min"=>{"$min"=>"$order_amount"}, "sum"=>{"$sum"=>"$order_amount"}, "avg"=>{"$avg"=>"$order_amount"}}}]} (2.4292ms)

I've also tried using the `moped` aggregate command with `Order.collection.aggregate` and that doesn't seem to work either.

	Order.collection.aggregate(
		{ 
			'$group' => { 
				'_id' => '$order_amount', 
				'totalOrder' => { '$sum' => '$order_amount' }		
			}
		}
	)

Any help please?

**Comment by alup** [comment]
Have you tried `Order.sum(:cents)`? For mongoid v3 every `Money` object is serialized to the ` { cents: <value>, currency_iso: <value> }`

**Comment by marcocanderle** [comment]
Hi, I came looking for a similar answer than yours. I wanted to share that I was able to sum money-rails values using something like this: 

Order.sum("order_amount.cents")

This will return just the cents values from the Money-rails structure: { cents: <value>, currency_iso: <value> }

So in order to get the sum in money-rails format you would use:
Order.sum("order_amount.cents").to_money

Hope it helps.

**Comment by netwire88** [comment]
Thanks @marcocanderle , I think that worked! Awesome.

**Comment by marcocanderle** [comment]
Hey @netwire88, I did further tests and the .to_money conversion doesn't work because it takes the sum result with an extra .00 (as I assume is stored on the money-rails format on the cents field). 
So if your sum gives 500, you'll get 500.00 as a result, and the to_money conversion will mistankely return an amount of $50000 instead of $500

I'm not sure why this is the case, but I fixed that replacing the to_money conversion with the Money.new. So continuing with your example, we would use:

    Money.new(Order.sum("order_amount.cents"))

**Comment by netwire88** [comment]
Thanks, you are right @marcocanderle. I've made the changes.

**Comment by shifakhan** [comment]
@netwire88 Did you try Order.sum(&:order_amount) ?

**Comment by semmons99** [comment]
Closed due to inactivity.
