### ISSUE TITLE
Migration issues with Rails 4.2.1

### ISSUE THREAD

**Issue by npearson72** [RubyMoney/money-rails#322]
I'm getting the following error when I try to run my migrations (which work find in 4.1.9):

````
undefined method `add_money' for #<AddPricingToProduct:0x007f303025e218>/vagrant/db/migrate/20150321222026_add_pricing_to_product.rb:3:in `change'
NoMethodError: undefined method `add_money' for #<AddPricingToProduct:0x007f303025e218>
/vagrant/db/migrate/20150321222026_add_pricing_to_product.rb:3:in `change'
````

**Comment by JamesChevalier** [comment]
There's a section in the README that might help you, if you're using PostgreSQL. (Although I'm a little worried that this might not be the cause of your issue, because I'm not sure I would expect an 'undefined method' error in this case.)

##### Notice for Rails >= 4.2 and PG adapter

Due to the addition of the money column type for PostgreSQL in Rails 4.2, you will need to use add_monetize instead of add_money column. If you're adding the column within a create_table block, use t.monetize, and use remove_monetize to remove the column.

**Comment by npearson72** [comment]
That did the trick. Thank you!
