### ISSUE TITLE
Usability suggestion: accept Money when building Active Record models

### ISSUE THREAD

**Issue by brian-vogogo** [RubyMoney/money-rails#324]
I expected to use Money in constructors:
``` 
Transaction.new(amount: Money.new(1000, 'GBP'))
Transaction.build(amount: Money.new(1000, 'GBP'))
Transaction.create(amount: Money.new(1000, 'GBP'))
```
but the above give:
```
RuntimeError: Can't change readonly currency 'USD' to 'GBP' for field 'amount'
```

**Comment by brian-vogogo** [comment]
I learned this can be achieved using `with_model_currency`. On the model:

    monetize :amount_cent, with_model_currency: :amount_currency

I don't really understand why the error occurs without it.

**Comment by antstorm** [comment]
@brian-vogogo the error was raised because there's no writable attribute to store currency. Since the currency is different from the default one (USD in your case) the gem tried to persist it, but couldn't. `with_model_currency` tells the gem in which column/attribute to store currency, that's why it works.

**Comment by brian-vogogo** [comment]
I assumed `add_money` worked hand-in-hand with `monetize`. `add_money` adds both _cents and _currency columns by default so figured monetize would use them. Thanks.
