### ISSUE TITLE
add_monetize and locale

### ISSUE THREAD

**Issue by nicooga** [RubyMoney/money-rails#399]
For some reason, the migration helper `add_monetize` generates a column "<attr_name>_centavos" ("centavos" is spanish for "cents"). I don't know if this is expected behavior, but it was not expected for me and I couldn't find some one with the same "error".

Yes, I set my locale to es-AR

``` ruby
    config.i18n.available_locales = ["es-AR", "es"]
    config.i18n.default_locale = "es-AR"
    config.i18n.enforce_available_locales = false
    config.i18n.fallbacks = ["es-AR", "es", "en"]
```

... but I don't see the point, is a convention to keep variable names in english.

For the time being I resorted to just create the columns without using the macro, and with a new migration since I don't want to rollback on staging.

``` ruby
class SolveMigrationProblemWithMoneyOnTeachers < ActiveRecord::Migration
  def change
    remove_monetize :teachers, :hour_price

    add_column :teachers, :hour_price_cents, :integer, default: 0
    add_column :teachers, :hour_price_urrency, :string, default: "ARS"
  end
end
```

Just wanted to point this out as it seemed strange to me.

Cheers

**Comment by rizidoro** [comment]
same here , but when a set to Brazilian Portuguese... Did you find why?

**Comment by rizidoro** [comment]
So, digging into the `money` gem, it uses the `Subunit` whuch in `centavo` in BRL:
https://github.com/RubyMoney/money/blob/85159c7d8540bcac23f138372f5f64cecf2ca199/config/currency_iso.json

So this is not a issue.

**Comment by nicooga** [comment]
@rizidoro still it doesn't make sense for the cents column name to be localized. The currency can change any time.

**Comment by igneus** [comment]
This is even more interesting in case of default currency set to `:czk` (Czech Koruna), whose "cents" are called "haléř". money-rails isn't scared at all by the diacritics and happily creates database columns named e.g. `amount_haléřs`

**Comment by antstorm** [comment]
Going through the specs I didn't find anything related to this, so I guess it is non-intentional behaviour and should be removed. Happy to review & merge a PR for this one.

**Comment by antstorm** [comment]
@igneus since #425 is not getting reviewed/merged (plus it's a big change, so will probably go into the next version of `money-rails`) would be great to check out your solution for this issue and merge it.

**Comment by igneus** [comment]
> @antstorm: Going through the specs I didn't find anything related to this, so I guess it is a non-intentional behaviour and should be removed.

Actually there is this assertion showing that the behaviour is intentional.
https://github.com/RubyMoney/money-rails/blob/master/spec/configuration_spec.rb#L96

And here is the commit by which it was first introduced
https://github.com/RubyMoney/money-rails/commit/f0394eb8b3c4b9ff5674ef5cc19fcc97b02416d5

Is it still ok to remove this behaviour and only use a single universal suffix "_cents" for the name of the amount column?

**Comment by antstorm** [comment]
@igneus yeah, I think it should be updated explicitly in the initializer if somebody want's to use a different postfix, otherwise it only causes confusion. Also this might be breaking behaviour for people, so I'm thinking of adding this as part of 2.0.0 release.

@deepak since you're the original author of the change would be good to hear your opinion on this.

**Comment by antstorm** [comment]
@igneus I merged #425

**Comment by facundofarias** [comment]
Hey guys, so is there a way to avoid this behavior?
Thanks

**Comment by igneus** [comment]
@facundofarias You can explicitly set amount column name postfix in your money initializer, like

```ruby
MoneyRails.configure do |config|
    config.amount_column = {
      postfix: '_cents', # column name  postfix
    }
end
```
