### ISSUE TITLE
Ideas for changing the public API

### ISSUE THREAD

**Issue by antstorm** [RubyMoney/money-rails#420]
Hi all,

Had this idea for quite some time, now thinking of actually implementing it, but wanted to raise a discussion first to see what others think.

Basically I was thinking of changing the `monetize` method's footprint by inverting it to make it act more like `belongs_to` method. The main change is specifying the "virtual attribute" first and figuring out derivatives (subunit, currency) based on that. So the new `monetize` method would look like this:

```
monetize :price
```

From that we can easily determine the subunit by appending `amount_column[:postfix]` and currency by appending `currency_column[:postfix]`, both can be overriden of course.

The main reason for this proposal is clarity — it's clear that you are creating a new `price` attribute, plus people are used to that pattern because of `belongs_to`.

I know it's a breaking change to the API and to me that's a major drawback for this, but maybe we can create another method to do that, leaving `monetize` intact while deprecating it.

What do you guys think? Worth a go? Bullshit?

**Comment by teoulas** [comment]
This looks like a nice to have clean-up, but the tradeoff is significant. Do you think keeping the same method name, but supporting both syntaxes is possible? For example, if the first argument has the suffix `_cents`, you use the old method signature, if it doesn't, you use the new one. I'm not sure if it's even possible, since I'm not aware of all the possible options you can pass to `monetize`. I mostly use the defaults.

If that's not possible, a new method is a decent alternative (`has_money` or something), but maybe it's just not worth it.

**Comment by antstorm** [comment]
Yes, you're right the tradeoff is quite significant. And simply dropping the old one is not an option, but I do like `has_many` approach. We can use that as the main method, while rewiring `monetize` to call it underneath, while still maintaining it's original signature.

I would avoid trying to detect a signature based on `_cents`, since it's configurable and depends on few other things. And will make it even messier than it is right now :)
