### ISSUE TITLE
Optional validations

### ISSUE THREAD

**Issue by Nerian** [RubyMoney/money-rails#449]
Hi,

Is there any chance these validations could be made optional?

https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_model/validator.rb#L37-L41

My use case is the following: 

The input html tag with type number stores the value always using the point separator, ie: '50.70'. This is no issue when you try to save that value when you are using the english locale. But when you use the spanish locale, for example, the decimal separator is comma (,). So validations fail when trying to save the 50.70 value that my model gets.

I considered some kind of utility code in each place where I store a money value, but it is way to many places. And it would be error prone to try to catch all places in which this could be used.

The workaround I am using right now is just to redefine the `validate_each` method with the relevant part commented out.

**Comment by antstorm** [comment]
@Nerian very good discovery. In order to patch it you might wanna subclass `MoneyValidator` overriding those validation methods to return `true` and then using you own class to validate input, skipping the default one with `disable_validation: false` or `MoneyRails.include_validations = false`.

But it raises an interesting question regarding the locales and formatting. Before it was assumed that each currency comes with it's own decimal separator and formatting rules, but it actually seems to be locale dependent.

What would be an expected behaviour of this in your country? Accept both `.` and `,` as decimal separators or `,` only? Or should it be based on user's locale?

**Comment by Nerian** [comment]
In Spain we write numbers like this:

1.000.500,40 €

Using 'dots' for thousand separator, and commas as the decimal separator. 

The current Money's behaviour in regards to parsing is strictly correct. But the issue is that as a web developer you are not going to always get the input in the way the user's locale is set. For example, the 'input' tag with the 'number' type is going to have a value set in the english way of writing numbers (dot as decimal separator) and it will not accept any other separator. When I try to modify the input field to have a value of '50,20' it shows nothing.

Ideally, Money will pretty print money values using the rules of the locale, as it does right now, but it should be able to parse values regardless of the current locale or currency rules.

All these inputs should be equivalent, no matter the locale:

"1.000.456,50 €"
"€ 1,000,456.50"
"1000456.50"
"1000456,50"
"1000456,5"
"1000456.5"

Your idea of redefining the validation methods instead of validate_each was a good one. A lot less chance of something going wrong on an update. I am currently doing this and having no problem so far:

```
module MoneyRails
  module ActiveModel
    class MoneyValidator < ::ActiveModel::Validations::NumericalityValidator
      def value_has_too_many_decimal_points
        false
      end

      def thousand_separator_after_decimal_mark
        false
      end

      def invalid_thousands_separation
        false
      end
    end
  end
end
```

**Comment by antstorm** [comment]
Right, so it seems that `monetize` (which `money-rails` uses) actually supports all those cases:

```ruby
>> Monetize.assume_from_symbol = true
=> true
>> Monetize.parse "1.000.456,50 €"
=> #<Money fractional:100045650 currency:USD>
>> Monetize.parse "€ 1,000,456.50"
=> #<Money fractional:100045650 currency:EUR>
>> Monetize.parse "1000456.50"
=> #<Money fractional:100045650 currency:USD>
>> Monetize.parse "1000456,50"
=> #<Money fractional:100045650 currency:USD>
>> Monetize.parse "1000456,5"
=> #<Money fractional:100045650 currency:USD>
>> Monetize.parse "1000456.5"
=> #<Money fractional:100045650 currency:USD>
```

I'll check what's actually wrong here, because it should be calling `.to_money` on the input, which goes directly into `Monetize.parse`

**Comment by jokklan** [comment]
Hi, I just experienced this issue as well and I guess it's actually a bug right? I mean a browser always submits with dot as decimal point, so the params received will also always be with dot. However when using many europeans languages is the decimal point a comma, and money-rails will then (wrongly) give a validation error, because it tries to parse a number with dot notation as a number with comma notation.

**Comment by jokklan** [comment]
The check that fails in validation is `invalid_thousands_separation`

**Comment by tommyalvarez** [comment]
What happened to this? It's impossible to use money rails on a field through a form for latin american locales

**Comment by antstorm** [comment]
@jokklan @tommyalvarez are you guys using I18n in your apps? Asking this because in order to parse these values correctly we need to know which symbols should be used as a decimal mark and a thousands separator. `Monetize`can make an intelligent guess, but you won't really want guesswork when it comes to money inputs.

**Comment by tommyalvarez** [comment]
@antstorm I am using i18n in my app. However my browser/system locale is in another language, easier for programming and keyboard layout, so the input type='number' in chrome accepts '.' only as a decimal mark. That said, from what i understand after reading the html5 specification, form number input values sent to the backend are standarized, locale agnostic and sent as "xx.y" always, respecting floating point natural notation in computers. Moreover in the rails controller, when assigning parameters to a model, the ones that correspond to float attributes will be converted to rails numbers which also respect "xx.y" notation. 
So i don't think number fields of a model should be validated against a specific locale format. Model number attributes backed by money-rails should be just that, numbers, locale agnostic.

I'm sure there was a discussion in the past about how money-rails would handle values for the "#{field}=" method, so i lack the context of that discussion, and possibly many edge cases i'm not seeing right now. So what would be the solution other than monkey patching and turning off validations, to deal with forms that are in a different locale than the backend ?

**Comment by jokklan** [comment]
Hi @antstorm. Yes I'm using I18n as well, and also [rails-i18n](https://github.com/svenfuchs/rails-i18n) which actually has a key for [currency separator](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/da.yml#L154)). 

However it would also help a lot, to be able to disable the validations on a model-to-model basis, and maybe even include it manually. Somethink like `validate_monetized :price, if: :some_conditional_method?`. That way can you skip validations for form inputs with number fields, where they always are submitted with dot format, as @tommyalvarez wrote, but still allow free string inputs when neccesary.

**Comment by antstorm** [comment]
@tommyalvarez I completely agree with you on the locale-agnostic side. The problem here is that `money-rails` was made very flexible on the input side, so the problem arises when a string is submitted instead of a number. Unless I'm misreading the problem, but I think that was the original issue in this thread. 

@tommyalvarez @jokklan does disabling validation using `disable_validation: true` or `numerically: false` work for you?

**Comment by tommyalvarez** [comment]
@antstorm No they would not work since i need to validate that the number is greater than or equal to 0 with for e.g.:

```
monetize :price_cents, numericality: {
    greater_than_or_equal_to: 0
  }
```

`disable_validations: true` or `numericality: false` would go in the opposite direction, letting the model save negative numbers. Unless i can redefine it later with a classic `validates :price_cents, numericality` ...

Is it possible?

**Comment by antstorm** [comment]
@tommyalvarez it should be possible, have you tried it? So these validations have been somewhat of a pain point and I'm looking into how these can be sorted out. One thing to note here is that there is a flag `subunit_numericality`, which performs the checks on the actual field, rather than a virtual attribute.

**Comment by b-nik** [comment]
I too came across this today. 

1) \<input type=\"number\"\> will always sent a float with a dot separator, which makes sense.
2) Money also validates the price if it's a string, which also makes sense:
```ruby
Model.create(price: "3.4") # validation error for EUR
Model.create(price: "3,4") # ok for EUR
Model.create(price: 3.4) # ok for all, since it's a float
```

However params get to the controller as string, so the combination of 1 and 2 makes for an interesting bug - not sure what's the best way to tackle it. I wonder if indicating that we want to parse the string as a float would be a good compromise to keep both options?
```ruby
Model.create(price_float: "3.4") # casts the string as float 
Model.create(price: "3.4") # validates as normal
```

My temporary solution right now to this is to call to_f on the param field after I permit them in the controller, so the model gets them as floats.

**Comment by tommyalvarez** [comment]
For anyone reaching here, i never tried to use **disable_validation: true**, but did use **numericality: false** on the monetize options. Just added normal validations afterwards to the attribute. Also i surrendered and ended up using this in an initializer:
```

# Monkey Patch for money validations
module MoneyRails
  module ActiveModel
    class MoneyValidator < ::ActiveModel::Validations::NumericalityValidator
      def value_has_too_many_decimal_points
        false
      end

      def thousand_separator_after_decimal_mark
        false
      end

      def invalid_thousands_separation
        false
      end
    end
  end
end
```

Which leaves money-rails locale agnostic for validations

**Comment by b-nik** [comment]
@tommyalvarez  what happens with this if you provide rubbish to the model?
```ruby
Model.create(price: "not-a-number")
```

**Comment by tommyalvarez** [comment]
@b-nik you can do:

`validates :price, numericality: {...rails_standard_validations...}`
