### ISSUE TITLE
column names can't be the same as model accessor

### ISSUE THREAD

**Issue by anujbiyani** [RubyMoney/money-rails#450]
I noticed this fails:
```
class Foo < ActiveRecord::Base
  monetize :amount, as: :amount
end
```
because of issue https://github.com/RubyMoney/money-rails/issues/427

I think there's actually a way to avoid the stack overflow error, but I wanted to ask before submitting a PR.

If we change [this line](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L183) to
```
amount = read_attribute(subunit_name)
```
then the overflow issue is gone. The obvious problem is that we also lose `*args` (because `read_attribute` does not take any args other than the attribute name); is this a problem? Does `money-rails` need to support calling of attributes with args?

Can you think of any other reasons why `read_attribute` wouldn't work instead of `public_send`?

**Comment by antstorm** [comment]
@anujbiyani I think that `*args` can be removed, because there's no trace of it being used anywhere even in tests. Best way to be sure is to remove it and run the tests.

I'm not sure how much sense does masking the actual attribute make, but it's definitely something that people had difficulties with and it might make `money-rails` integration slightly easier for bigger apps with legacy.

**Comment by anujbiyani** [comment]
> integration slightly easier for bigger apps with legacy

That's my motivation. We're trying to change our column names to match the postfix scheme, but ideally we'd do that in multiple stages.

> there's no trace of it being used anywhere even in tests. Best way to be sure is to remove it and run the tests

Excellent I'll give it a go, thanks for the feedback.

**Comment by anujbiyani** [comment]
Hmm looks like two tests fail using `read_attribute`, both around when the value is an `attr_accessor` or a method instead of a pure DB column:
```
Failures:

  1) MoneyRails::ActiveRecord::Monetizable.monetize correctly assigns objects to a accessor attribute
     Failure/Error: expect(product.accessor_price.cents).to eq(123)

     NoMethodError:
       undefined method `cents' for nil:NilClass
     # ./spec/active_record/monetizable_spec.rb:510:in `block (3 levels) in <top (required)>'

  2) MoneyRails::ActiveRecord::Monetizable.monetize for model with currency column: constructs the money object from the mapped method value
     Failure/Error: expect(transaction.total).to eq(Money.new(3000, :usd))

       expected: #<Money fractional:3000 currency:USD>
            got: nil

       (compared using ==)
     # ./spec/active_record/monetizable_spec.rb:700:in `block (4 levels) in <top (required)>'

Finished in 1.12 seconds (files took 0.98753 seconds to load)
240 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/active_record/monetizable_spec.rb:506 # MoneyRails::ActiveRecord::Monetizable.monetize correctly assigns objects to a accessor attribute
rspec ./spec/active_record/monetizable_spec.rb:698 # MoneyRails::ActiveRecord::Monetizable.monetize for model with currency column: constructs the money object from the mapped method value
```

Something like this would work but it makes me pretty nervous because it can easily lead to a stack overflow if the db column exists but is null:
```
      def read_monetized(name, subunit_name, *args)
        # Get the cents
        amount = read_attribute(subunit_name) || public_send(subunit_name, *args)
```

At this point I think it's probably better to just close this issue and encourage people to migrate their databases to have `*_cents` columns.

**Comment by antstorm** [comment]
Yeah, good call. Since the check for that case is in place it might be worth leaving that.

One thing that I wanted to implement some time ago (which might be related to this case) — instead of guessing amount and currency every time we might wanna cache that in `monetized_attributes`. That way we know exactly where these values should come from allowing us to look in the right place instead of trying everything until there's some result.

Do you think that your implementation could benefit from having the above mentioned mechanism in place?

**Comment by anujbiyani** [comment]
I think it would! Seems like it would get around the stack overflow by letting us intelligently choose when we should use `read_attribute` vs `public_send`. Depends on what's cached inside `monetized_attributes`, I suppose.

Either way, going to close this. Thanks for the help!
