### ISSUE TITLE
How to stop nil values from being initialized with 0 Money object?

### ISSUE THREAD

**Issue by ESWAT** [RubyMoney/money-rails#487]
Take the following model as an example:

    class Product < ApplicationRecord
        monetize :price_cents, numericality: { greater_than_or_equal_to: 0 }
        …
    }

with this schema

    create_table "products", id: :serial, force: :cascade do |t|
        t.integer "price_cents", null: false
        …
    end

When I create a new `Product` that has nil `price` instead of the value being nil I get a `Money` object with the value of 0. Undesirable for my use case because I’d rather have empty values set explicitly rather than implicitly.

Setting `default:nil` in `config.amount_column` only gives me the desired behaviour on initialization, but then `price` gets set to the `Money` object of 0 if `Product` is updated with `price` still set to nil.

How do I stop this behaviour?

EDIT: My issue is similar to #384 but not specific to mongoid

**Comment by antstorm** [comment]
@ESWAT good point, I think this one needs a PR to resolve. There are 2 ways of thinking here, the first one is where you're coming from — you want explicit `nil` indicating that something wasn't set as opposed to being set to zero. However the other way of looking at his is trying to avoid `nil` at all costs, minimising well known ruby problems like `NoMethodError` and so on.

In this particular scenario the gem probably needs to be more flexible, allowing user to control the default value of the attribute.

**Comment by antstorm** [comment]
@ESWAT looking into this issue, have you tried adding `allow_nil: true` to your `monetize` call?

**Comment by ESWAT** [comment]
@antstorm hmm it’s been a while but judging from my code it looks like I hadn’t used that option.

I’ll use that and if you don’t hear from me then it means it worked and thanks 👍

**Comment by antstorm** [comment]
@ESWAT great, good luck! :)

**Comment by ESWAT** [comment]
Went through my solution again but `allow_nil: true` wasn’t sufficient.

I technically don’t want to allow a nil value to pass ActiveRecord validation, so with this flag on a nil value will hit the DB and return an exception. However that flag does prevent the Money object from returning 0 when I want it to be nil.

My ruby-fu is not great but I could try to make a PR for this. This seems more of an issue with the `money` gem than `money-rails` though?

**Comment by gregpardo** [comment]
Also having this same problem. If I set to nil the model still returns valid even if I have presence: true on the column. It retains the value it was set to.

**Comment by rikas** [comment]
Same problem here! :(

**Comment by antstorm** [comment]
@gregpardo @rikas any of you up for a quick PR to fix this?

**Comment by BrianHawley** [comment]
OK, the quick solution to this issue is to add the `allow_nil: true` option to `monetize`, but then adding a separate presence validation on the field. If `allow_nil: true` is set then the `MoneyRails::ActiveRecord::Monetizable` `write_monetized` method won't convert the nil to a 0 with `to_money`. Then, on save or validation, the separate presence validation will block the object from being saved because the field is not present.

This also makes the ShouldaMatchers `validate_presence_of` test work.

I think that there are real advantages to keeping both kinds of behavior: the conversion to 0 and not. The above workaround makes that happen. However, I'd want to make sure that if an attribute isn't specified then it should be initialized with the field's default value, rather than nil. That's something to consider when making the tests for this change.
