### ISSUE TITLE
Money amount interpreted as cents pre v1.6.2 if default currency was cents-based, but not after

### ISSUE THREAD

**Issue by shioyama** [RubyMoney/money-rails#491]
I'm not sure if this is a bug before or after v1.6.2, but it's definitely something that should be flagged.

This change: https://github.com/RubyMoney/money-rails/compare/v1.6.1...v1.6.2 had a drastic effect on how money fields are interpreted depending on the value of the default currency.

I've created a repository and some specs to demonstrate this: https://github.com/degica/money-rails-test

See these spec results: https://travis-ci.org/degica/rails-money-test/builds/252703835

Specs are run with v1.6.1 and v1.6.2, and with default currency set to JPY and USD in context blocks.

In 1.6.1, with default currency set to "JPY", this is what we see (and expected):

```ruby
payment = Payment.new(amount: 100, currency: "USD")
payment.amount.cents
#=> 100

payment = Payment.new(amount: 100, currency: "JPY")
payment.amount.cents
#=> 100
```

So everything is cents-based. This happens to work well for us, and I assumed this was the way things worked. However, I didn't realize, but apparently if you default currency is "USD", this is what you saw previous to 1.6.2:

```ruby
payment = Payment.new(amount: 100, currency: "USD")
payment.amount.cents
#=> 10000

payment = Payment.new(amount: 100, currency: "JPY")
payment.amount.cents
#=> 10000
```

which seems completely crazy to me. Everything (including JPY, which are not dollars) is being treated as if it's dollars. (This I guess was the issue raised in #421.)

As of v1.6.2, however, this has changed and now the `amount` is interpreted as either a cent amount or dollar amount depending on the currency.

```ruby
payment = Payment.new(amount: 100, currency: "USD")
payment.amount.cents
#=> 10000

payment = Payment.new(amount: 100, currency: "JPY")
payment.amount.cents
#=> 100
```

I guess this makes more sense, but there does not seem to be any indication that this change was conscious (no clear mention of it anywhere, no major version change, etc.)

We luckily caught this but you can imagine that it very well could have had a huge impact on our money calculations. I'm amazed this has not been flagged earlier since the change happened more than a year ago.

I previously tried to "fix" this problem in #490 but then realized that the code is perhaps not wrong, since I do find the change as of v1.6.2 more internally consistent. However I do think there should be a warning somewhere! Can you confirm my interpretation here is correct?

Thanks!

**Comment by shioyama** [comment]
The commit is: c3c97ad21b10c09e45ba5a5a9119db79693c5b79

It was made to fix #421.

**Comment by antstorm** [comment]
@shioyama good shout, I remember that commit and this problem is still something I'm thinking about. Basically it happens when you assign both `monetize`d attribute and currency at the same time. In fact if you look at that commit you've mentioned — it actually re-assigns the amount column when **reading** the attribute.

What happens there is you're assigning 2 attributes sequentially. First the `amount` gets set to 100 converted to `Money`, using the default currency. At this point the `amount` is also getting pre-cached. Then the `currency` gets set. At this point if there would be no reading of the attribute involved the values would have been stored incorrectly. Next when you read the attribute in `payment.amont.cents`, the cached value is compared against the amount and currency (which is now different) and gets re-instantiated while also updating the DB field to a new value since the currency has different subunit-to-unit. Basically it's a big mess and it needs a solution.

An easy solution is to never assign a Fixnum to a `monetize`d attribute, because it's open to interpretation based on a currency that is resolved at the moment of assignment. In your case you can safely assign `amount_cents` and `currency`, or just `amount`, but use an instance of `Money` as value.

While it works this leaves issue described in #421 open — you don't want users to fill in `_cents` via UI, but allowing them to edit `monetize`d attribute directly exposes a problem mentioned above… you can definitely alter `params` in your controller, but that's not good enough for a gem, so needs a better way of doing this.

Your opinion on this is greatly appreciated!

**Comment by shioyama** [comment]
Thanks, that explanation basically confirms my understanding but it's great to have it clearly in writing, because the code is hard to grok and there's not much mention (as far as I can find) of how this works in any documentation.

I think that one of the things to me that makes the change very confusing is that Money itself is cents based. In *any* currency, when you pass an integer as the first argument initializing a `Money` object, it is interpreted as *cents*, not as the unit of the currency:

```ruby
Money.new(100, "JPY").cents
#=> 100

Money.new(100, "USD").cents
#=> 100
```

Money *could* do the same as money-rails, and interpret the number as either dollars or cents depending on the unit of the currency, **but it doesn't**.

I think this is a potential source of confusion, but I also acknowledge that most people using money-rails have a default currency that is dollar based, so presumably they are already accustomed to decimals being converted to dollars.

That said, if your default currency was JPY, I think it was reasonable to assume (previous to 1.6.2) that everything, including money-rails, was also cents based, such that `Payment.new(amount: 100, currency: "USD")` would interpret the amount as 100 *cents*, regardless of the currency. I assumed this and my team assumed this.

I understand that the current way of dealing with amount works better for forms, where you want the user to enter a number in whatever the unit of the currency is they are entering. It generally does't make sense for a user to enter a cents amount if the currency is USD.

So... I'm a bit torn. For now we're updating our code to handle this situation correctly, based on the latest version of money-rails.

At the very least there should be some specs covering this in detail. Another idea would be to have an option to make *all* amounts cents or dollar based, regardless of currency (i.e. reverting #421, but in a way that is independent of your default currency).

**Comment by antstorm** [comment]
I've commented on your PR.

I do agree with the need for a spec covering this use case, but also it seems like this change is causing more issues than it solves. It introduces quite a bit of complexity and is frankly a mess. Unless there's a better solution to this without problematic side-effects I'm thinking that reverting it might be a good idea.
