### ISSUE TITLE
Overriding the setter throws an error

### ISSUE THREAD

**Issue by amingilani** [RubyMoney/money-rails#507]
My values come with a lot of weird whitespace and padding so, as recommended by the [docs](http://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Overwriting+default+accessors) I tried to override the accessors

```
  def price=(value)
    price = value.strip
    super(price)
  end
  
  def quantity=(quantity)
    quantity = quantity.strip
    super(quantity)
  end
```

This resulted in the following error:

```
     NoMethodError:
       super: no superclass method `price=' for #<Item:0x007faf30f2f620>
       Did you mean?  price
```

Is there a workaround for this? For the moment, i'm going to strip it in the controller, but this definitely feels like something the model should be doing.

**Comment by samstickland** [comment]
I think this will work if you `prepend` a module instead:

```
class MyRecord < ApplicationRecord
  module StripValues
    def price=(value)
      price = value.strip
      super(price)
    end
  
    def quantity=(quantity)
      quantity = quantity.strip
      super(quantity)
    end
  end

  prepend StripValues
```

The problem is that the setter methods are defined (via `define_method`) in your active record class itself, so there is no setter method in `ActiveRecord::Base` to call. Prepending a module however will prepend the method in *your* active record class, so when it calls super it will should call the right methods.. That is, in the example above when `MyRecord#price=` is called, it will first invoke `MyRecord::StripValues#price=` and then when that calls super it will invoke `MyRecord#price=`

**Comment by amingilani** [comment]
Thank you!

**Comment by achernik** [comment]
There is also another way to handle this problem:

```ruby
  alias price_from_monetize= price=

  def price=(value)
    price = value.strip
    self.price_from_monetize(value)
  end
```

**Comment by rockwellll** [comment]
> There is also another way to handle this problem:
> 
> ```ruby
>   alias price_from_monetize= price=
> 
>   def price=(value)
>     price = value.strip
>     self.price_from_monetize = price
>   end
> ```

I'm sorry but im dumbfounded and cant seem to understand how this works. Could you clarify? Thanks.

**Comment by dorianmariefr** [comment]
@rockwellll A common idiom is to do `alias old_price= price=` so you have an alias of the current `price=` method named `old_price=` that will be used later.

Then we override `price=`, do our custom code (the strip) and call the aliased method (the old_price= method, here named `price_from_monetize=`)

hope this helps
