### ISSUE TITLE
cannot use this gem in conjunction with config.i18n.fallbacks = true in rails (odd behaviour)

### ISSUE THREAD

**Issue by jasdeepsingh** [RubyMoney/money-rails#516]
I spent countless hours debugging this issue and was almost at the verge of having a bald head (due to extensive hair pulling)

Everything was good in development:

### **config/development.rb**
```
config.i18n.fallbacks = false
```

```
I18n.locale = :en
Model.money_field.format
=> "R$1,399.00"

I18n.locale = :pt
Model.money_field.format
=> "R$1.399,00"
```

Production environment was a whole different ball game:
### **config/production.rb**
```
config.i18n.fallbacks = true
```

```
I18n.locale = :en
Model.money_field.format
=> "R$1,399.00"

I18n.locale = :pt
Model.money_field.format
=> "R$1,399.00"   <----- NO LOCALIZED FORMATTING HAPPENING HERE. Expectation is: => "R$1.399,00"
```

Setting `config.i18n.fallbacks = false` did the trick for me?

Now, i'm not sure if this is a bug or not, It sure did took me on a never ending wild-goose-chase. Hope this could save someone some precious time.

If it does happen to be a bug, a fix will be highly appreciated!

**Comment by antstorm** [comment]
@jasdeepsingh thanks for posing this! I'm looking into the underlying issue, but can not replicate this behaviour. Can you please list the versions of the gems you are using (like `rails`, `money`, `money-rails`, `i18n`)? Also where do the localization rules are coming from, it is `rails-i18n` gem or a custom defined rules? In case it's custom — which rules are you using?

**Comment by indifferentalex** [comment]
We had a very similar issue, perhaps it was the case here as well, although I understand that it might not be of much use posting it now seeing the date the issue was opened:

For us it was incorrectly set translation strings for I18n currencies, we had set the `currency` key at the same level of the `number` key, instead, as per the [docs](https://github.com/RubyMoney/money#localization), it should go inside the `number` key. What was happening is that with fallbacks enabled, upon not finding the required `currency` strings, it would fall back to the default locale (as is intended with `fallbacks = true`), afterwards it would again not find the `currency` strings, therefore it would end up using the `delimiter` and `separator` from the `number` strings instead.

e.g.

Wrong:

```ruby
  number:
    format:
      delimiter: '.'
      separator: ','
  currency:
    format:
      delimiter: '.'
      separator: ','
```

Right:

```ruby
  number:
    format:
      delimiter: '.'
      separator: ','
      precision: 2
```

**Comment by antstorm** [comment]
@jasdeepsingh can you please confirm that the proposed solution solves your issue?

@indifferentalex thanks for posting! 👍
