### ISSUE TITLE
Does not play nice with encryption

### ISSUE THREAD

**Issue by justinlyman** [RubyMoney/money-rails#543]
I am trying to use money-rails with active record and the symmetric-encryption gem [https://github.com/rocketjob/symmetric-encryption](https://github.com/rocketjob/symmetric-encryption).

Example:
Model: Customer

the column name would be :encrypted_income_cents

I set the field as encrypted in the model with:
`attr_encrypted :income_cents, random_iv: true, :type => :integer`
 
This gives me the ability to get and set the encrypted field using income_cents.

If I monetize the field:
`monetize :income_cents, as: 'income', allow_nil: false`

I get the error:
`ActiveModel::MissingAttributeError: can't write unknown attribute 'income_cents'
from /usr/local/bundle/gems/activemodel-5.2.1/lib/active_model/attribute.rb:207:in 'with_value_from_database'`

If I monetize the field using the column name, it monetizes the field correctly, but it bypasses the encryption and stores it in the database as plain text:
  `monetize :encryted_income_cents, as: 'income', allow_nil: false`

Any help would be much appreciated.

**Comment by antstorm** [comment]
@justinlyman the problem here is that `money-rails` overrides the setter for `income_cents` when validation is used. I'll need to double check why exactly are we doing this.

Looking through the implementation it seems that you can get away with passing `disable_validation: true` to you `monetize` call. This will however disable the validation, but you should be able to implement it yourself using `validate`.

Please tell me if that works, while I try to figure out why we need to override setter.
