### ISSUE TITLE
Forms fields invalid format when the i18n locale decimals delimiter is a comma

### ISSUE THREAD

**Issue by skuark** [RubyMoney/money-rails#554]
Hi. I have a problem with money in an application localized to Spanish.

The default Spanish delimiter for decimals is a comma. If I display a price with the locale backend set to `:i18n`, the price appears ok, with the comma: `21,95 €`.

The problem occurs with the form to edit this price. I use the HTML5 `type="number"` field with the rails `number_field` helper.

```
<%= form_for @book do |f| %>
  <%= f.number_field :price %>
<% end %>
```

If the locale is set to `:en` this renders:

```
<input type="number" value="21.95">
```

But when the locale is set to `:es`, the result is:

```
<input type="number" value="21,95">
```

And the comma is not a supported for the input number values in the HTML5 standard, so the field appears empty when loading the resource edit page.

If I change the money locale backend to `nil` globally the forms looks good, but the format when displaying the price uses the standard dot instead of the comma (`21.95 €`).

I've tried to address the issue forcing the value to use the dot representation in the input values:

```
<%= form_for @book do |f| %>
  <%= f.number_field :price, value: f.object.price.to_s.gsub(",", ".") %>
<% end %>
```

But obviously, it's not an ideal solution. Some other cleaner idea?

**Comment by antstorm** [comment]
@skuark there are couple of solutions to this that I can think of. Most likely you wanna keep `locale_backend` set to `:i18n`, because that controls your formatted output. In order to force decimal mark be a dot you can pass that as an option to the `#format` — `.format(decimal_mark: '.')`.

But the cleanest solution would probably be using `.to_f` on the money object since you're not looking for a formatted string, but rather a numeric representation of the money object.

Hope that makes sense.

**Comment by pioz** [comment]
Same problem, really annoying... Any workaround?

**Comment by skuark** [comment]
@pioz Take a look to my comment here: https://github.com/RubyMoney/money-rails/issues/538#issuecomment-441218984

I hope that this workaround help you.

**Comment by sabatesduran** [comment]
I have the same problem.

I changed the `number_field` with a `text_field` that has a JS event listener function to parse it to a comma using `Number.prototype.toLocalString`.

I have two languages in my website `:en` and `:nl` all works with comma when I'm in the Dutch website but not when I'm in the English one and I have already changed the `backend_locale` to `:currency`.

I could use I18n to check what to look for for the input field and that will probably work, but I don't understand why this is not working since it should not be attached to the language anymore.

**Comment by antstorm** [comment]
FYI, I've opened a PR that will respect your `Money.locale_backend` settings when performing input validations — #567.

**Comment by micdahl** [comment]
> FYI, I've opened a PR that will respect your `Money.locale_backend` settings when performing input validations — #567.

Does that resolve the initial problem and if how? Still ran into this problem.

My current workaround is the following helper, which is a generalisation of @skuark`s initial approach:

```
module ApplicationHelper
  def number_field(object_name, method, options = {})
    unless options.has_key?(:value)
      object = self.instance_variable_get("@#{object_name}")
      value = object.public_send(method)
      value = value.to_s.gsub(",", ".")
      options = options.merge({ value: value })
    end
    super(object_name, method, options)
  end
end
```

Just implemented, but seems to work. Still not very nice in my opinion, as it is something which should run out of the box on my belief. But as a workaround it seems ok. Even not sure, if the underlaying problem is limited to `money-rails`, or if this is something which makes problems in other situations, too. i18n is a nerves destroyer!

**Comment by antstorm** [comment]
@micdahl the linked PR fixes validation on the backend, but still won't fix the displayed format. And I don't think this can be fixed on the gem's side because `f.number_field :price` won't tell the attribute how it wants it to be formatted. Couple of options here:

1. Redefine `Money#to_s` to add `decimal_mark: '.'` to the `format` call. But make sure to use `.format` (not `.to_s`) whenever you need to display localized money

2. Add your helper to `ActionViewExtension` of this gem to make it available for everyone and potentially money patch the form's `#number_field` to always format with a `.`
