### ISSUE TITLE
group and sum calculations

### ISSUE THREAD

**Issue by mmahalwy** [RubyMoney/money-rails#571]
Noticed this issue which might be a bit dated: https://github.com/RubyMoney/money-rails/issues/497

Curious what's the best way to do things like `#group` with `#sum` or any active record calculations? Right now, I have it return the numbers in cents which I have to then convert to `Money` object.

**Comment by antstorm** [comment]
@mmahalwy yeah, thanks for reminding, I need to pick it up again. Not entirely sure how the `#sum` would work, though, as you would probably need to group in order to calculate a sum…

**Comment by mmahalwy** [comment]
@antstorm correct. I am not a sql wizard sadly. The way I solved it is through plain old `group_by` but feel it's not scalable with large datasets.

**Comment by antstorm** [comment]
@mmahalwy yep, which just might be the best way of doing it. The reason being that these query methods are supposed to translate directly to SQL. This way you are sort of writing SQL, but using a DSL. Which is why `#sum` that not only adds a `SUM(amount_cents)`, but also `GROUP BY amount_currency` might be confusing in some cases.
