### ISSUE TITLE
Config's default_format being ignored

### ISSUE THREAD

**Issue by nitsujri** [RubyMoney/money-rails#582]
Ruby: 2.6.5
Rails: 6.0.0
MoneyRails: 1.13.2

It appears the `default_format` isn't being considered

```
irb(main):001:0> MoneyRails::Configuration.default_format
=> {:no_cents_if_whole=>false, :symbol=>nil, :sign_before_symbol=>nil}
irb(main):002:0> MoneyRails::Configuration.no_cents_if_whole
=> nil
```
```
##### Even when default_format is true, it's ignored ########
irb(main):002:0> MoneyRails::Configuration.default_format
=> {:no_cents_if_whole=>true, :symbol=>nil, :sign_before_symbol=>nil}
irb(main):003:0> MoneyRails::Configuration.no_cents_if_whole
=> nil
```
```
##### Manually setting works #########################
irb(main):004:0> include MoneyRails::ActionViewExtension
=> Object
irb(main):005:0> MoneyRails::Configuration.no_cents_if_whole = false
=> false
irb(main):006:0> humanized_money(Money.new(10_00, 'USD'))
=> "10.00"
irb(main):008:0> MoneyRails::Configuration.no_cents_if_whole = nil
=> nil
irb(main):009:0> humanized_money(Money.new(10_00, 'USD'))
=> "10"
```

Here's an empty project exhibiting the behavior - empty rails and money-rails being the only thing added with init.

https://github.com/nitsujri/money-default-format-issues

Thanks for this great gem! -Justin

**Comment by antstorm** [comment]
This looks like a default behaviour:

> `humanized_money` and `humanized_money_with_symbol` will not render the cents part if it contains only zeros, unless `config.no_cents_if_whole` is set to `false` in the `money.rb` configuration (default: true).
> Note that the `config.default_format` will be overwritten by `config.no_cents_if_whole`.
So `humanized_money` will ignore `config.default_format = { no_cents_if_whole: false }` if you don't set `config.no_cents_if_whole = false`.

But I agree that it's confusing and doesn't make much sense. I think the intention was not to let `default_format` affect `humanized_money`, but expose some configurability via `MoneyRails::Configuration.no_cents_if_whole`.

It kind feels that it should not be possible to configure it at all since it's an opinionated convenience method. And it that doesn't work, there's always `Money#format` with all the options.

**Comment by nitsujri** [comment]
@antstorm, Ah I see that now and you're right. That is quite confusing, but it is what it is. I'll close this since it's expected behavior.
