### ISSUE TITLE
Using money-rails with mongoid: How to set currency per model instance

### ISSUE THREAD

**Issue by jattoabdul** [RubyMoney/money-rails#596]
I'm currently using:

money-rails v1.12
rails v6
mongoid v7

I would like to set the default currency to be used by each model instance.

I have set the field in my model like below

`field :price, type: Money, with_model_currency: :currency`

But when I try to create or fetch records I get this error

```
Mongoid::Errors::InvalidFieldOption
message:
  Invalid option :with_model_currency provided for field :price.
```
How do I use the `with_model_currency` option in a rails mongoid application?
How else can I handle money in a rails mongoid application?

**Comment by antstorm** [comment]
@jattoabdul money works a bit differently with `mongoid` compare to `activerecord`. Since `mongo` can have nested fields, specifying the `type: Money` should enable serialization/deserialization for you. 

`with_model_currency` (along with most other ones) is the options available on `activerecord` only.
